#ifndef HUFFMAN_COMPRESS_H
#define HUFFMAN_COMPRESS_H
/*
 * Huffman tables for compressing discrete Gaussian samples (z1,z2,z3).
 * Auto-generated by scripts/huffman_compress.py
 *
 * Encoding scheme (per coefficient):
 *   [1 sign bit (1=negative)]
 *   [Huffman code for bucket index of |v|]
 *   [(k-1) fixed-width offset bits if bucket k>=1]
 */
#include <stdint.h>
#include <stddef.h>
#include "params.h"

/* Z1: 13504 coeffs, sigma=582380223.29 */
#define HUFFMAN_Z1_COMPRESSED_BYTES_MAX 52882
#define HUFFMAN_Z1_MAX_BUCKET 33
#define HUFFMAN_Z1_ESCAPE_BUCKET 34
static const uint32_t huffman_z1_code[] = {
    0x2ff80001, /* k=0: 31 bits */
    0x17fc0001, /* k=1: 30 bits */
    0x0bfe0001, /* k=2: 29 bits */
    0x05ff0001, /* k=3: 28 bits */
    0x02ff8001, /* k=4: 27 bits */
    0x017fc001, /* k=5: 26 bits */
    0x00bfe001, /* k=6: 25 bits */
    0x005ff001, /* k=7: 24 bits */
    0x002ff801, /* k=8: 23 bits */
    0x0017fc01, /* k=9: 22 bits */
    0x000bfe01, /* k=10: 21 bits */
    0x0005ff01, /* k=11: 20 bits */
    0x0002ff81, /* k=12: 19 bits */
    0x00017fc1, /* k=13: 18 bits */
    0x0000bfe1, /* k=14: 17 bits */
    0x00005ff1, /* k=15: 16 bits */
    0x00002ff9, /* k=16: 15 bits */
    0x000017fd, /* k=17: 14 bits */
    0x00000bff, /* k=18: 13 bits */
    0x000002fe, /* k=19: 11 bits */
    0x0000017e, /* k=20: 10 bits */
    0x000000be, /* k=21: 9 bits */
    0x0000005e, /* k=22: 8 bits */
    0x0000002e, /* k=23: 7 bits */
    0x00000016, /* k=24: 6 bits */
    0x0000000a, /* k=25: 5 bits */
    0x00000004, /* k=26: 4 bits */
    0x00000007, /* k=27: 4 bits */
    0x00000000, /* k=28: 2 bits */
    0x00000002, /* k=29: 2 bits */
    0x00000003, /* k=30: 2 bits */
    0x00000006, /* k=31: 4 bits */
    0x000005fe, /* k=32: 12 bits */
    0x2ff80000, /* k=33: 31 bits */
    0x00000000, /* k=34: 0 bits */
};
static const uint8_t huffman_z1_len[] = {
    31, /* k=0 */
    30, /* k=1 */
    29, /* k=2 */
    28, /* k=3 */
    27, /* k=4 */
    26, /* k=5 */
    25, /* k=6 */
    24, /* k=7 */
    23, /* k=8 */
    22, /* k=9 */
    21, /* k=10 */
    20, /* k=11 */
    19, /* k=12 */
    18, /* k=13 */
    17, /* k=14 */
    16, /* k=15 */
    15, /* k=16 */
    14, /* k=17 */
    13, /* k=18 */
    11, /* k=19 */
    10, /* k=20 */
    9, /* k=21 */
    8, /* k=22 */
    7, /* k=23 */
    6, /* k=24 */
    5, /* k=25 */
    4, /* k=26 */
    4, /* k=27 */
    2, /* k=28 */
    2, /* k=29 */
    2, /* k=30 */
    4, /* k=31 */
    12, /* k=32 */
    31, /* k=33 */
    0, /* k=34 */
};

/* Z2: 4736 coeffs, sigma=311304.54 */
#define HUFFMAN_Z2_COMPRESSED_BYTES_MAX 12156
#define HUFFMAN_Z2_MAX_BUCKET 22
#define HUFFMAN_Z2_ESCAPE_BUCKET 23
static const uint32_t huffman_z2_code[] = {
    0x0003fc01, /* k=0: 20 bits */
    0x0001fe01, /* k=1: 19 bits */
    0x0000ff01, /* k=2: 18 bits */
    0x00007f81, /* k=3: 17 bits */
    0x00003fc1, /* k=4: 16 bits */
    0x00001fe1, /* k=5: 15 bits */
    0x00000ff1, /* k=6: 14 bits */
    0x000007f9, /* k=7: 13 bits */
    0x000003fd, /* k=8: 12 bits */
    0x000001ff, /* k=9: 11 bits */
    0x0000007e, /* k=10: 9 bits */
    0x0000003e, /* k=11: 8 bits */
    0x0000001e, /* k=12: 7 bits */
    0x0000000e, /* k=13: 6 bits */
    0x00000006, /* k=14: 5 bits */
    0x00000002, /* k=15: 4 bits */
    0x00000000, /* k=16: 3 bits */
    0x00000003, /* k=17: 3 bits */
    0x00000002, /* k=18: 2 bits */
    0x00000003, /* k=19: 2 bits */
    0x00000002, /* k=20: 3 bits */
    0x000000fe, /* k=21: 10 bits */
    0x0003fc00, /* k=22: 20 bits */
    0x00000000, /* k=23: 0 bits */
};
static const uint8_t huffman_z2_len[] = {
    20, /* k=0 */
    19, /* k=1 */
    18, /* k=2 */
    17, /* k=3 */
    16, /* k=4 */
    15, /* k=5 */
    14, /* k=6 */
    13, /* k=7 */
    12, /* k=8 */
    11, /* k=9 */
    9, /* k=10 */
    8, /* k=11 */
    7, /* k=12 */
    6, /* k=13 */
    5, /* k=14 */
    4, /* k=15 */
    3, /* k=16 */
    3, /* k=17 */
    2, /* k=18 */
    2, /* k=19 */
    3, /* k=20 */
    10, /* k=21 */
    20, /* k=22 */
    0, /* k=23 */
};

/* Z3: 256 coeffs, sigma=114957846.74 */
#define HUFFMAN_Z3_COMPRESSED_BYTES_MAX 990
#define HUFFMAN_Z3_MAX_BUCKET 31
#define HUFFMAN_Z3_ESCAPE_BUCKET 32
static const uint32_t huffman_z3_code[] = {
    0x0b7ffe00, /* k=0: 28 bits */
    0x0b7ffe01, /* k=1: 28 bits */
    0x05bfff01, /* k=2: 27 bits */
    0x02dfff81, /* k=3: 26 bits */
    0x016fffc1, /* k=4: 25 bits */
    0x00b7ffe1, /* k=5: 24 bits */
    0x005bfff1, /* k=6: 23 bits */
    0x002dfff9, /* k=7: 22 bits */
    0x0016fffd, /* k=8: 21 bits */
    0x000b7fff, /* k=9: 20 bits */
    0x0002dffe, /* k=10: 18 bits */
    0x00016ffe, /* k=11: 17 bits */
    0x0000b7fe, /* k=12: 16 bits */
    0x00005bfe, /* k=13: 15 bits */
    0x00002dfe, /* k=14: 14 bits */
    0x000016fe, /* k=15: 13 bits */
    0x00000b7e, /* k=16: 12 bits */
    0x000005be, /* k=17: 11 bits */
    0x000002de, /* k=18: 10 bits */
    0x0000016e, /* k=19: 9 bits */
    0x000000b6, /* k=20: 8 bits */
    0x0000005a, /* k=21: 7 bits */
    0x0000002c, /* k=22: 6 bits */
    0x0000002f, /* k=23: 6 bits */
    0x0000000a, /* k=24: 4 bits */
    0x00000004, /* k=25: 3 bits */
    0x00000000, /* k=26: 2 bits */
    0x00000003, /* k=27: 2 bits */
    0x00000001, /* k=28: 2 bits */
    0x0000002e, /* k=29: 6 bits */
    0x0005bffe, /* k=30: 19 bits */
    0x00000000, /* k=31: 0 bits */
    0x00000000, /* k=32: 0 bits */
};
static const uint8_t huffman_z3_len[] = {
    28, /* k=0 */
    28, /* k=1 */
    27, /* k=2 */
    26, /* k=3 */
    25, /* k=4 */
    24, /* k=5 */
    23, /* k=6 */
    22, /* k=7 */
    21, /* k=8 */
    20, /* k=9 */
    18, /* k=10 */
    17, /* k=11 */
    16, /* k=12 */
    15, /* k=13 */
    14, /* k=14 */
    13, /* k=15 */
    12, /* k=16 */
    11, /* k=17 */
    10, /* k=18 */
    9, /* k=19 */
    8, /* k=20 */
    7, /* k=21 */
    6, /* k=22 */
    6, /* k=23 */
    4, /* k=24 */
    3, /* k=25 */
    2, /* k=26 */
    2, /* k=27 */
    2, /* k=28 */
    6, /* k=29 */
    19, /* k=30 */
    0, /* k=31 */
    0, /* k=32 */
};

/* Offset bits for bucket k */
static inline int huffman_offset_bits(int k) { return (k <= 1) ? 0 : k - 1; }

/* ── Huffman Pack / Unpack for Gaussian samples ── */
size_t huffman_pack_z1(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_pack_z2(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_pack_z3(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_unpack_z1(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);
size_t huffman_unpack_z2(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);
size_t huffman_unpack_z3(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);

/* ── Compact bit-packing for uniform-in-R_q elements ── */
/* Each coefficient uses 58 bits (= ceil(log2(q_show))) instead of 64.
 * Saves ~9.4% over naive 8-byte packing. */

#define COMPACT_UNIFORM_BITS  58   /* ceil(log2(PARAM_Q_SHOW)) */
#define COMPACT_UNIFORM_BYTES(ncoeffs) (((ncoeffs) * COMPACT_UNIFORM_BITS + 7) / 8)

size_t compact_pack_uniform(uint8_t *out, const int64_t *coeffs, size_t count);
size_t compact_unpack_uniform(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);

/* ── Compact bit-packing for challenge polynomial c ── */
/* Each coefficient in [-rho, rho] with rho=8 → 5 bits/coeff.
 * Encoded as: (centered_value + 8) in [0,16], stored in 5 bits. */

#define COMPACT_CHALLENGE_BITS   5
#define COMPACT_CHALLENGE_OFFSET PARAM_RHO_SHOW  /* = 8 */
#define COMPACT_CHALLENGE_BYTES(ncoeffs) (((ncoeffs) * COMPACT_CHALLENGE_BITS + 7) / 8)

size_t compact_pack_challenge(uint8_t *out, const int64_t *coeffs, size_t count);
size_t compact_unpack_challenge(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);

/* Precomputed packed byte sizes for show_proof_t fields */
#define COMPACT_TA_BYTES  COMPACT_UNIFORM_BYTES(PARAM_D_SHOW * PARAM_N_SHOW)       /* 10672 */
#define COMPACT_TB_BYTES  COMPACT_UNIFORM_BYTES(PARAM_ARP_DIV_N_L_SHOW * PARAM_N_SHOW) /* 5104 */
#define COMPACT_H_BYTES   COMPACT_UNIFORM_BYTES(PARAM_L_SHOW * PARAM_N_SHOW)       /* 3248 */
#define COMPACT_T1_BYTES  COMPACT_UNIFORM_BYTES(PARAM_N_SHOW)                      /* 464 */
#define COMPACT_C_BYTES   COMPACT_CHALLENGE_BYTES(PARAM_N_SHOW)                    /* 40 */
#define COMPACT_CTRC_BYTES 4

/* Total compressed show proof size */
#define COMPACT_SHOW_PROOF_TOTAL_BYTES \
    (COMPACT_TA_BYTES + COMPACT_TB_BYTES + \
     HUFFMAN_Z3_COMPRESSED_BYTES_MAX + \
     COMPACT_H_BYTES + COMPACT_T1_BYTES + COMPACT_C_BYTES + COMPACT_CTRC_BYTES + \
     HUFFMAN_Z1_COMPRESSED_BYTES_MAX + HUFFMAN_Z2_COMPRESSED_BYTES_MAX)

#endif
