# -*- coding: utf-8 -*-
"""
Fast Huffman code generation using Gaussian CDF (erf).
Outputs: C header with tables + theoretical size analysis.
"""
from math import sqrt, log2, ceil, floor, pi, exp, erf, log
import heapq, os

# ── Sigma values for Show proof ──
CONFIGS = {
    "Z1": {"sigma": 582380223.29, "count": 211 * 64, "desc": "m1*n = 13504 coeffs"},
    "Z2": {"sigma": 311304.54,    "count": 74 * 64,   "desc": "m2*n = 4736 coeffs"},
    "Z3": {"sigma": 114957846.74, "count": 256,        "desc": "ARP 256 coeffs"},
}
SEC = 128
HEADER_PATH = "../code/include/huffman_compress.h"

def phi(x):
    """Standard normal CDF using erf."""
    return 0.5 * (1.0 + erf(x / sqrt(2.0)))

def bucket_prob(sigma, k):
    """Probability that |v| falls in bucket k.
    Bucket 0: |v|=0
    Bucket k>=1: |v| in [2^(k-1), 2^k - 1]
    """
    if k == 0:
        return 1.0 / (sigma * sqrt(2.0 * pi))
    lo = (1 << (k - 1)) - 0.5  # continuity correction
    hi = (1 << k) - 0.5
    p_pos = phi(hi / sigma) - phi(lo / sigma)
    return 2.0 * p_pos  # both signs

def offset_bits(k):
    """Fixed-width offset bits for bucket k."""
    return max(0, k - 1)

def theoretical_entropy(sigma):
    """Theoretical entropy bound: 0.5 + log2(sigma * sqrt(2*pi*e)) bits."""
    return 0.5 + log2(sigma * sqrt(2.0 * pi * exp(1.0)))

def build_huffman(probs):
    """Build Huffman tree. Returns {symbol: (code_int, bit_len)}."""
    if not probs:
        return {}
    counter = [0]
    heap = []
    paths = {}
    for s, p in probs.items():
        counter[0] += 1
        heap.append((p, counter[0], [s]))
        paths[s] = []
    heapq.heapify(heap)
    while len(heap) > 1:
        p1, _, s1 = heapq.heappop(heap)
        p2, _, s2 = heapq.heappop(heap)
        for s in s1: paths[s].insert(0, 0)
        for s in s2: paths[s].insert(0, 1)
        counter[0] += 1
        heapq.heappush(heap, (p1 + p2, counter[0], s1 + s2))
    result = {}
    for s, bits in paths.items():
        ci = 0
        for b in bits: ci = (ci << 1) | b
        result[s] = (ci, len(bits))
    return result

def analyze(name, cfg):
    sigma = cfg["sigma"]
    count = cfg["count"]
    desc = cfg["desc"]

    # Find tail bound
    c = sqrt(2.0 * (SEC + 1) * log(2.0))
    max_v = ceil(c * sigma)
    max_k = floor(log2(max_v)) + 1

    # Escape bucket for rare outliers
    esc_k = max_k + 1

    # Compute bucket probabilities
    probs = {}
    for k in range(0, max_k + 1):
        probs[k] = bucket_prob(sigma, k)
    # Remainder goes to escape bucket
    total = sum(probs.values())
    probs[esc_k] = max(0.0, 1.0 - total)

    # Build Huffman
    active = {k: p for k, p in probs.items() if p > 1e-300}
    codes = build_huffman(active)

    # Expected bits per coefficient
    avg_bits = 0.0
    for k in range(0, max_k + 2):
        if k not in probs: continue
        p = probs[k]
        if p < 1e-300: continue
        clen = codes[k][1]
        off = offset_bits(k) if k <= max_k else 48  # escape: 48 raw bits
        avg_bits += p * (1 + clen + off)  # 1 = sign bit

    entropy = theoretical_entropy(sigma)
    naive_bytes = count * 8  # 8 bytes per coeff
    compressed_bytes = (avg_bits * count) / 8.0

    print(f"\n{'='*60}")
    print(f"  {name}: sigma={sigma:.2e}, {desc}")
    print(f"{'='*60}")
    print(f"  Tail bound: c={c:.2f}, max|v|={max_v}, max_bucket={max_k}")
    print(f"  Buckets: {len(active)} active")
    for k in sorted(codes.keys()):
        ci, cl = codes[k]
        lo = 1<<(k-1) if k>=1 else 0
        hi = (1<<k)-1 if k>=1 else 0
        off = offset_bits(k) if k<=max_k else 48
        print(f"    k={k:2d}: |v|∈[{lo:>12d},{hi:>12d}] "
              f"prob={probs[k]:.4e} huff={ci:0{cl}b}({cl}b) off={off}b")
    print(f"  Expected bits/coeff: {avg_bits:.2f}")
    print(f"  Theoretical entropy: {entropy:.2f} bits")
    print(f"  Compressed: {count} coeffs -> {compressed_bytes:.0f}B = {compressed_bytes/1024:.2f} KB")
    print(f"  Naive: {naive_bytes}B = {naive_bytes/1024:.1f} KB")
    print(f"  Ratio: {naive_bytes/compressed_bytes:.2f}x")

    return {
        "name": name, "sigma": sigma, "count": count,
        "codes": codes, "max_k": max_k, "esc_k": esc_k,
        "compressed_bytes": compressed_bytes, "naive_bytes": naive_bytes,
        "avg_bits": avg_bits, "entropy": entropy
    }

def gen_header(results):
    h = """#ifndef HUFFMAN_COMPRESS_H
#define HUFFMAN_COMPRESS_H
/*
 * Huffman tables for compressing discrete Gaussian samples (z1,z2,z3).
 * Auto-generated by scripts/huffman_compress.py
 *
 * Encoding scheme (per coefficient):
 *   [1 sign bit (1=negative)]
 *   [Huffman code for bucket index of |v|]
 *   [(k-1) fixed-width offset bits if bucket k>=1]
 */
#include <stdint.h>
#include <stddef.h>

"""
    for r in results:
        h += f"/* {r['name']}: {r['count']} coeffs, sigma={r['sigma']:.2f} */\n"
        h += f"#define HUFFMAN_{r['name']}_COMPRESSED_BYTES_MAX {ceil(r['compressed_bytes']) + 64}\n"
        h += f"#define HUFFMAN_{r['name']}_MAX_BUCKET {r['max_k']}\n"
        h += f"#define HUFFMAN_{r['name']}_ESCAPE_BUCKET {r['esc_k']}\n"
        codes = r['codes']
        h += f"static const uint32_t huffman_{r['name'].lower()}_code[] = {{\n"
        for k in range(r['esc_k'] + 1):
            ci, cl = codes.get(k, (0, 0))
            h += f"    0x{ci:08x}, /* k={k}: {cl} bits */\n"
        h += "};\n"
        h += f"static const uint8_t huffman_{r['name'].lower()}_len[] = {{\n"
        for k in range(r['esc_k'] + 1):
            _, cl = codes.get(k, (0, 0))
            h += f"    {cl}, /* k={k} */\n"
        h += "};\n\n"

    h += """/* Offset bits for bucket k */
static inline int huffman_offset_bits(int k) { return (k <= 1) ? 0 : k - 1; }

/* Pack / Unpack API */
size_t huffman_pack_z1(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_pack_z2(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_pack_z3(uint8_t *out, const int64_t *coeffs, size_t count);
size_t huffman_unpack_z1(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);
size_t huffman_unpack_z2(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);
size_t huffman_unpack_z3(int64_t *out, const uint8_t *in, size_t packed_bytes, size_t count);

#endif
"""
    return h

# ── Main ──
print("Huffman Compression Analysis for Show Proof Gaussian Samples")
results = []
total_comp = 0.0
total_naive = 0.0
total_ent = 0.0

for name, cfg in CONFIGS.items():
    r = analyze(name, cfg)
    results.append(r)
    total_comp += r["compressed_bytes"]
    total_naive += r["naive_bytes"]
    total_ent += (r["entropy"] + 1) * r["count"] / 8.0  # +1 for sign bit

print(f"\n{'='*60}")
print(f"  OVERALL SUMMARY")
print(f"{'='*60}")
print(f"  Naive (64-bit):     {total_naive:.0f} B = {total_naive/1024:.2f} KB")
print(f"  Huffman compressed: {total_comp:.0f} B = {total_comp/1024:.2f} KB")
print(f"  Entropy bound:      {total_ent:.0f} B = {total_ent/1024:.2f} KB")
print(f"  Compression ratio:  {total_naive/total_comp:.2f}x")
print(f"  vs entropy limit:   {total_comp - total_ent:.0f} B overhead ({100*total_comp/total_ent - 100:.1f}%)")

header = gen_header(results)
os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
with open(HEADER_PATH, 'w') as f:
    f.write(header)
print(f"\n  Header written to: {HEADER_PATH}")
